-- MySQL Script generated by MySQL Workbench
-- Sat Feb 17 06:38:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema desafioglobo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desafioglobo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafioglobo` DEFAULT CHARACTER SET utf8 ;
USE `desafioglobo` ;

-- -----------------------------------------------------
-- Table `desafioglobo`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafioglobo`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `canal` VARCHAR(75) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Maria de Fátima','E-mail','mariadefatima@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Almir Joaquim','Telefone','2579-3303',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Maria Bethânia','E-mail','mariabethania@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Priscila chaves','E-mail','priscilachaves@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Ricardo de Souza Alvares','Telefone','2587-4466',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Amanda Nunes','Telefone','8999-2781',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Roberto Oliveira','E-mail','robertooliveira@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Mauricio Carvalho','E-mail','mauriciocarvalho@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Bia Arantes','E-mail','biaarantes@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Michele Souza','Telefone','2579-303',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Dayanna Silva','E-mail','Dayanasilva@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Helen Santos','E-mail','helensantos@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Mariana Araujo','Telefone','9987-4466',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Patricia Santos','Telefone','8959-2781',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Joaquim Santos','E-mail','joaquimSantos@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Fernanda Faria','E-mail','fernandafaria@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Patricia Faria','E-mail','patriciafaria@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Josefina Barbosa','Telefone','2879-3313',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Sandra Santos','E-mail','sandrasantos@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Jose Santos','E-mail','josesantos@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Francisco Silva','Telefone','3847-4466',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Roberto Teixeira','E-mail','robertoteixeira@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Anderson Alvarenga','Telefone','2579-3303',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Helton Santos','E-mail','heltonsantos@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Raquel Honorato','E-mail','raquelhonorato@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Fabiana Oliveira','Telefone','2587-4466',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Felícia Borges','Telefone','8999-2781',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Gustavo Borges','E-mail','gustavoborges@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Flavio Bernades','E-mail','flaviob@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Bernardo Alcantara','E-mail','bernardoalcantara@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Solange Gomes','Telefone','2579-303',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Fernando Alvarenga','E-mail','fernandoalvarenga@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Clara Medeiros','E-mail','claramedeiros@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Zélia Silva ','Telefone','9987-4466',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Oliver Bastos','Telefone','8959-2781',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Caio Medeiros','E-mail','caiomedeiros@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Alberto Faria','E-mail','albertofaria@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Bruno Borges','E-mail','Bruno Borges@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Bianca santos','Telefone','2879-3313',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Daniela campos','E-mail','danielacampos@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Diego Santos','E-mail','diegosantos@gmail.com',null);
INSERT INTO `desafioglobo`.`contato`(`nome`,`canal`,`valor`,`observacao`)VALUES('Marcio Santos','Telefone','3847-4466',null);

